module.exports = {
  upload:function(req,res){
    req.file('avatar').upload({
      dirname: "/Users/zhuang/Desktop/images"
    },function (err, uploadedFiles) {
      if (err) return res.negotiate(err);

      return res.json({
        message: uploadedFiles.length + ' file(s) uploaded successfully!'
      });
    });
  },
  file:function(req,res){
    var action = req.param("action");
    if(action=="config"){
      return res.json({
        "imageActionName":"uploadimage",
        "imageFieldName":"upfile",
        "imageMaxSize":2048000,
        "imageAllowFiles":[
          ".png",
          ".jpg",
          ".jpeg",
          ".gif",
          ".bmp"
        ],
        "imageCompressEnable":true,
        "imageCompressBorder":1600,
        "imageInsertAlign":"none",
        "imageUrlPrefix":"",
        "imagePathFormat":"/server/ueditor/upload/image/{yyyy}{mm}{dd}/{time}{rand:6}",
        "scrawlActionName":"uploadscrawl",
        "scrawlFieldName":"upfile",
        "scrawlPathFormat":"/server/ueditor/upload/image/{yyyy}{mm}{dd}/{time}{rand:6}",
        "scrawlMaxSize":2048000,
        "scrawlUrlPrefix":"",
        "scrawlInsertAlign":"none",
        "snapscreenActionName":"uploadimage",
        "snapscreenPathFormat":"/server/ueditor/upload/image/{yyyy}{mm}{dd}/{time}{rand:6}",
        "snapscreenUrlPrefix":"",
        "snapscreenInsertAlign":"none",
        "catcherLocalDomain":[
          "127.0.0.1",
          "localhost",
          "img.baidu.com"
        ],
        "catcherActionName":"catchimage",
        "catcherFieldName":"source",
        "catcherPathFormat":"/server/ueditor/upload/image/{yyyy}{mm}{dd}/{time}{rand:6}",
        "catcherUrlPrefix":"",
        "catcherMaxSize":2048000,
        "catcherAllowFiles":[
          ".png",
          ".jpg",
          ".jpeg",
          ".gif",
          ".bmp"
        ],
        "videoActionName":"uploadvideo",
        "videoFieldName":"upfile",
        "videoPathFormat":"/server/ueditor/upload/video/{yyyy}{mm}{dd}/{time}{rand:6}",
        "videoUrlPrefix":"",
        "videoMaxSize":102400000,
        "videoAllowFiles":[
          ".flv",
          ".swf",
          ".mkv",
          ".avi",
          ".rm",
          ".rmvb",
          ".mpeg",
          ".mpg",
          ".ogg",
          ".ogv",
          ".mov",
          ".wmv",
          ".mp4",
          ".webm",
          ".mp3",
          ".wav",
          ".mid"
        ],
        "fileActionName":"uploadfile",
        "fileFieldName":"upfile",
        "filePathFormat":"/server/ueditor/upload/file/{yyyy}{mm}{dd}/{time}{rand:6}",
        "fileUrlPrefix":"",
        "fileMaxSize":51200000,
        "fileAllowFiles":[
          ".png",
          ".jpg",
          ".jpeg",
          ".gif",
          ".bmp",
          ".flv",
          ".swf",
          ".mkv",
          ".avi",
          ".rm",
          ".rmvb",
          ".mpeg",
          ".mpg",
          ".ogg",
          ".ogv",
          ".mov",
          ".wmv",
          ".mp4",
          ".webm",
          ".mp3",
          ".wav",
          ".mid",
          ".rar",
          ".zip",
          ".tar",
          ".gz",
          ".7z",
          ".bz2",
          ".cab",
          ".iso",
          ".doc",
          ".docx",
          ".xls",
          ".xlsx",
          ".ppt",
          ".pptx",
          ".pdf",
          ".txt",
          ".md",
          ".xml"
        ],
        "imageManagerActionName":"listimage",
        "imageManagerListPath":"/server/ueditor/upload/image/",
        "imageManagerListSize":20,
        "imageManagerUrlPrefix":"",
        "imageManagerInsertAlign":"none",
        "imageManagerAllowFiles":[
          ".png",
          ".jpg",
          ".jpeg",
          ".gif",
          ".bmp"
        ],
        "fileManagerActionName":"listfile",
        "fileManagerListPath":"/server/ueditor/upload/file/",
        "fileManagerUrlPrefix":"",
        "fileManagerListSize":20,
        "fileManagerAllowFiles":[
          ".png",
          ".jpg",
          ".jpeg",
          ".gif",
          ".bmp",
          ".flv",
          ".swf",
          ".mkv",
          ".avi",
          ".rm",
          ".rmvb",
          ".mpeg",
          ".mpg",
          ".ogg",
          ".ogv",
          ".mov",
          ".wmv",
          ".mp4",
          ".webm",
          ".mp3",
          ".wav",
          ".mid",
          ".rar",
          ".zip",
          ".tar",
          ".gz",
          ".7z",
          ".bz2",
          ".cab",
          ".iso",
          ".doc",
          ".docx",
          ".xls",
          ".xlsx",
          ".ppt",
          ".pptx",
          ".pdf",
          ".txt",
          ".md",
          ".xml"
        ]
      });
    }else if(action=="listimage"){
      var start = req.param("start");
      var size = req.param("size");
      var data = [{
        mtime:1476032488,
        url:"/images/aiwrap.png"
      },{
        mtime:1476032488,
        url:"/images/phone-case.png"
      }];
      res.json({
        list:data,
        start:start,
        state:"SUCCESS",
        total:data.length
      });
    }
  }
};
